### ISSUE TITLE
milestones

### ISSUE THREAD

**Issue by project-lev0** [project-lev0/lev0#1]
## 1.0.0-pre7
- [x] apply new page view request constructor
- [ ] add navigator on page view
- [ ] add favorite into exh service

## next milestone
- [ ] using vuex for data model
- [ ] split heavy components(viewer, etc)
